[book]
title = "TONGO â€” by FAT SOLUTIONS"
authors = ["Fat Solutions"]
language = "en"
# multilingual = false
src = "src"

[build]
build-dir = "book"

[output.html]
mathjax-support = true
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/fatlabsxyz/tongo"
edit-url-template = "https://github.com/fatlabsxyz/tongo/edit/master/packages/tongo-sdk/docs/{path}"
additional-css = ["theme/custom.css"]
additional-js = ["theme/footer.js"]

[output.html.search]
enable = true

[output.html.fold]
enable = false

[output.html.playground]
editable = false
